BRAND_MAP = \
{'calamax': 'ColaMax',
 'caunchbite': 'CrunchBite',
 'celamax': 'ColaMax',
 'ceunchbite': 'CrunchBite',
 'coaamax': 'ColaMax',
 'coeamax': 'ColaMax',
 'colaaax': 'ColaMax',
 'colaeax': 'ColaMax',
 'colamax': 'ColaMax',
 'colamex': 'ColaMax',
 'colamsx': 'ColaMax',
 'colamxx': 'ColaMax',
 'colamzx': 'ColaMax',
 'colasax': 'ColaMax',
 'colaxax': 'ColaMax',
 'colazax': 'ColaMax',
 'colemax': 'ColaMax',
 'colsmax': 'ColaMax',
 'colxmax': 'ColaMax',
 'colzmax': 'ColaMax',
 'cosamax': 'ColaMax',
 'coxamax': 'ColaMax',
 'cozamax': 'ColaMax',
 'cranchbite': 'CrunchBite',
 'crenchbite': 'CrunchBite',
 'crsnchbite': 'CrunchBite',
 'cruachbite': 'CrunchBite',
 'cruechbite': 'CrunchBite',
 'crunahbite': 'CrunchBite',
 'cruncaBite': 'CrunchBite',
 'cruncabite': 'CrunchBite',
 'cruncebite': 'CrunchBite',
 'crunchaite': 'CrunchBite',
 'crunchbate': 'CrunchBite',
 'crunchbete': 'CrunchBite',
 'crunchbiae': 'CrunchBite',
 'crunchbiee': 'CrunchBite',
 'crunchbise': 'CrunchBite',
 'crunchbite': 'CrunchBite',
 'crunchbixe': 'CrunchBite',
 'crunchbize': 'CrunchBite',
 'crunchbste': 'CrunchBite',
 'crunchbxte': 'CrunchBite',
 'crunchbzte': 'CrunchBite',
 'cruncheite': 'CrunchBite',
 'crunchsite': 'CrunchBite',
 'crunchxite': 'CrunchBite',
 'crunchzite': 'CrunchBite',
 'cruncsbite': 'CrunchBite',
 'cruncxbite': 'CrunchBite',
 'crunczbite': 'CrunchBite',
 'crunehbite': 'CrunchBite',
 'crunshbite': 'CrunchBite',
 'crunxhbite': 'CrunchBite',
 'crunzhbite': 'CrunchBite',
 'cruschbite': 'CrunchBite',
 'cruxchbite': 'CrunchBite',
 'cruzchbite': 'CrunchBite',
 'crxnchbite': 'CrunchBite',
 'crznchbite': 'CrunchBite',
 'cslamax': 'ColaMax',
 'csunchbite': 'CrunchBite',
 'cxlamax': 'ColaMax',
 'cxunchbite': 'CrunchBite',
 'czlamax': 'ColaMax',
 'czunchbite': 'CrunchBite',
 'daughboy': 'DoughBoy',
 'deughboy': 'DoughBoy',
 'doaghboy': 'DoughBoy',
 'doeghboy': 'DoughBoy',
 'dosghboy': 'DoughBoy',
 'douahboy': 'DoughBoy',
 'douehboy': 'DoughBoy',
 'dougaboy': 'DoughBoy',
 'dougahboy': 'DoughBoy',
 'dougeboy': 'DoughBoy',
 'doughaoy': 'DoughBoy',
 'doughbay': 'DoughBoy',
 'doughbey': 'DoughBoy',
 'doughboy': 'DoughBoy',
 'doughbsy': 'DoughBoy',
 'doughbxy': 'DoughBoy',
 'doughbzy': 'DoughBoy',
 'dougheoy': 'DoughBoy',
 'doughsoy': 'DoughBoy',
 'doughxoy': 'DoughBoy',
 'doughzoy': 'DoughBoy',
 'dougsboy': 'DoughBoy',
 'dougxboy': 'DoughBoy',
 'dougzboy': 'DoughBoy',
 'doushboy': 'DoughBoy',
 'douxhboy': 'DoughBoy',
 'douzhboy': 'DoughBoy',
 'doxghboy': 'DoughBoy',
 'dozghboy': 'DoughBoy',
 'dsughboy': 'DoughBoy',
 'dxughboy': 'DoughBoy',
 'dzughboy': 'DoughBoy',
 'fazzpop': 'FizzPop',
 'fezzpop': 'FizzPop',
 'fiazpop': 'FizzPop',
 'fiezpop': 'FizzPop',
 'fiszpop': 'FizzPop',
 'fixzpop': 'FizzPop',
 'fizapop': 'FizzPop',
 'fizepop': 'FizzPop',
 'fizspop': 'FizzPop',
 'fizxpop': 'FizzPop',
 'fizzaop': 'FizzPop',
 'fizzeop': 'FizzPop',
 'fizzpap': 'FizzPop',
 'fizzpep': 'FizzPop',
 'fizzpop': 'FizzPop',
 'fizzpsp': 'FizzPop',
 'fizzpxp': 'FizzPop',
 'fizzpzp': 'FizzPop',
 'fizzsop': 'FizzPop',
 'fizzxop': 'FizzPop',
 'fizzzop': 'FizzPop',
 'fizzzpop': 'FizzPop',
 'fszzpop': 'FizzPop',
 'fxzzpop': 'FizzPop',
 'fzzzpop': 'FizzPop',
 'fzzzpops': 'FizzPop',
 'patatoking': 'PotatoKing',
 'petatoking': 'PotatoKing',
 'poaatoking': 'PotatoKing',
 'poeatoking': 'PotatoKing',
 'posatoking': 'PotatoKing',
 'potaaoking': 'PotatoKing',
 'potaeoking': 'PotatoKing',
 'potasoking': 'PotatoKing',
 'potataking': 'PotatoKing',
 'potateking': 'PotatoKing',
 'potatoaing': 'PotatoKing',
 'potatoeing': 'PotatoKing',
 'potatokang': 'PotatoKing',
 'potatokeng': 'PotatoKing',
 'potatokiag': 'PotatoKing',
 'potatokieg': 'PotatoKing',
 'potatoking': 'PotatoKing',
 'potatokisg': 'PotatoKing',
 'potatokixg': 'PotatoKing',
 'potatokizg': 'PotatoKing',
 'potatoksng': 'PotatoKing',
 'potatokxng': 'PotatoKing',
 'potatokzng': 'PotatoKing',
 'potatosing': 'PotatoKing',
 'potatoxing': 'PotatoKing',
 'potatozing': 'PotatoKing',
 'potatsking': 'PotatoKing',
 'potatxking': 'PotatoKing',
 'potatzking': 'PotatoKing',
 'potaxoking': 'PotatoKing',
 'potazoking': 'PotatoKing',
 'potetoking': 'PotatoKing',
 'potstoking': 'PotatoKing',
 'potxtoking': 'PotatoKing',
 'potztoking': 'PotatoKing',
 'poxatoking': 'PotatoKing',
 'pozatoking': 'PotatoKing',
 'pstatoking': 'PotatoKing',
 'pstatokking': 'PotatoKing',
 'pxtatoking': 'PotatoKing',
 'pztatoking': 'PotatoKing',
 'saeettreat': 'SweetTreat',
 'seeettreat': 'SweetTreat',
 'sseettreat': 'SweetTreat',
 'swaettreat': 'SweetTreat',
 'sweattreat': 'SweetTreat',
 'sweeatreat': 'SweetTreat',
 'sweeetreat': 'SweetTreat',
 'sweestreat': 'SweetTreat',
 'sweetareat': 'SweetTreat',
 'sweetereat': 'SweetTreat',
 'sweetsreat': 'SweetTreat',
 'sweettaeat': 'SweetTreat',
 'sweetteeat': 'SweetTreat',
 'sweettraat': 'SweetTreat',
 'sweettreat': 'SweetTreat',
 'sweettreet': 'SweetTreat',
 'sweettrest': 'SweetTreat',
 'sweettrext': 'SweetTreat',
 'sweettrezt': 'SweetTreat',
 'sweettrsat': 'SweetTreat',
 'sweettrxat': 'SweetTreat',
 'sweettrzat': 'SweetTreat',
 'sweettseat': 'SweetTreat',
 'sweettxeat': 'SweetTreat',
 'sweettzeat': 'SweetTreat',
 'sweetxreat': 'SweetTreat',
 'sweetzreat': 'SweetTreat',
 'sweextreat': 'SweetTreat',
 'sweeztreat': 'SweetTreat',
 'swesttreat': 'SweetTreat',
 'swexttreat': 'SweetTreat',
 'swezttreat': 'SweetTreat',
 'swsettreat': 'SweetTreat',
 'swxettreat': 'SweetTreat',
 'swzettreat': 'SweetTreat',
 'sxeettreat': 'SweetTreat',
 'szeettreat': 'SweetTreat',
 'tatan': 'Titan',
 'tetan': 'Titan',
 'tiaan': 'Titan',
 'tiean': 'Titan',
 'tietan': 'Titan',
 'tisan': 'Titan',
 'titan': 'Titan',
 'titen': 'Titan',
 'titsn': 'Titan',
 'titxn': 'Titan',
 'titzn': 'Titan',
 'tixan': 'Titan',
 'tizan': 'Titan',
 'tstan': 'Titan',
 'txtan': 'Titan',
 'tztan': 'Titan',
 'zap': 'Zap'}

CATEGORY_MAP = \
{'bates': 'Snacks',
 'baverage': 'Beverages',
 'bavs': 'Beverages',
 'beaerage': 'Beverages',
 'betes': 'Snacks',
 'bevarage': 'Beverages',
 'beveeage': 'Beverages',
 'beveeages': 'Beverages',
 'beveraae': 'Beverages',
 'beveragas': 'Beverages',
 'beverage': 'Beverages',
 'beveragee': 'Beverages',
 'beverages': 'Beverages',
 'beveragess': 'Beverages',
 'beveragss': 'Beverages',
 'beveragzs': 'Beverages',
 'beverases': 'Beverages',
 'beveraxe': 'Beverages',
 'beverege': 'Beverages',
 'bevereges': 'Beverages',
 'beverges': 'Beverages',
 'beversge': 'Beverages',
 'beverxges': 'Beverages',
 'bevexages': 'Beverages',
 'bevezage': 'Beverages',
 'bevezages': 'Beverages',
 'bevs': 'Beverages',
 'bevsrage': 'Beverages',
 'bevsrages': 'Beverages',
 'bevxrages': 'Beverages',
 'bevzrage': 'Beverages',
 'bevzrages': 'Beverages',
 'bexerage': 'Beverages',
 'bexerages': 'Beverages',
 'bexs': 'Beverages',
 'bezerage': 'Beverages',
 'bezs': 'Beverages',
 'biaes': 'Snacks',
 'biees': 'Snacks',
 'bises': 'Snacks',
 'bites': 'Snacks',
 'bitss': 'Snacks',
 'bitxs': 'Snacks',
 'bitzs': 'Snacks',
 'bixes': 'Snacks',
 'bizes': 'Snacks',
 'bstes': 'Snacks',
 'bsverage': 'Beverages',
 'bsvs': 'Beverages',
 'bxtes': 'Snacks',
 'bxvs': 'Beverages',
 'bztes': 'Snacks',
 'bzvs': 'Beverages',
 'dainks': 'Beverages',
 'deinks': 'Beverages',
 'dranks': 'Beverages',
 'drieks': 'Beverages',
 'drinas': 'Beverages',
 'drinks': 'Beverages',
 'drinss': 'Beverages',
 'drinxs': 'Beverages',
 'drinzs': 'Beverages',
 'drixks': 'Beverages',
 'drsnks': 'Beverages',
 'drxnks': 'Beverages',
 'drznks': 'Beverages',
 'dsinks': 'Beverages',
 'dzinks': 'Beverages',
 'f&b - anacks': 'Snacks',
 'f&b - bev': 'Beverages',
 'f&b - bsv': 'Beverages',
 'f&b - saacks': 'Snacks',
 'f&b - snacas': 'Snacks',
 'f&b - snacks': 'Snacks',
 'f&b - snacss': 'Snacks',
 'f&b - snaeks': 'Snacks',
 'f&b - snscks': 'Snacks',
 'f&b - sxacks': 'Snacks',
 'f&b - szacks': 'Snacks',
 'f&b - xev': 'Beverages',
 'f&b -esnacks': 'Snacks',
 'f&b -ssnacks': 'Snacks',
 'f&b -zbev': 'Beverages',
 'f&b s snacks': 'Snacks',
 'f&ba- bev': 'Beverages',
 'f&be- bev': 'Beverages',
 'f&be- snacks': 'Snacks',
 'f&bs- snacks': 'Snacks',
 'f&bx- bev': 'Beverages',
 'f&bx- snacks': 'Snacks',
 'f&bz- snacks': 'Snacks',
 'f&s - snacks': 'Snacks',
 'f&z - snacks': 'Snacks',
 'fab - bev': 'Beverages',
 'fab - snacks': 'Snacks',
 'feb - snacks': 'Snacks',
 'fxb - snacks': 'Snacks',
 'fzb - bev': 'Beverages',
 'liqaid refreshment': 'Beverages',
 'liquad refreshment': 'Beverages',
 'liquid aefreshment': 'Beverages',
 'liquid refeeshment': 'Beverages',
 'liquid refresement': 'Beverages',
 'liquid refreshment': 'Beverages',
 'liquid refreshmxnt': 'Beverages',
 'liquid refreshxent': 'Beverages',
 'liquid refreshzent': 'Beverages',
 'liquid refressment': 'Beverages',
 'liquid refrxshment': 'Beverages',
 'liquid resreshment': 'Beverages',
 'liquid rsfreshment': 'Beverages',
 'liquidarefreshment': 'Beverages',
 'liquidarrefreshment': 'Beverages',
 'liquidxrefreshment': 'Beverages',
 'liquix refreshment': 'Beverages',
 'liqxid refreshment': 'Beverages',
 'liqzid refreshment': 'Beverages',
 'lisuid refreshment': 'Beverages',
 'lizuid refreshment': 'Beverages',
 'lzquid refreshment': 'Beverages',
 'pacaaged snacks': 'Snacks',
 'packagad snacks': 'Snacks',
 'packagea snacks': 'Snacks',
 'packaged anacks': 'Snacks',
 'packaged snacks': 'Snacks',
 'packaged ssacks': 'Snacks',
 'packagedasnacks': 'Snacks',
 'packagedesnacks': 'Snacks',
 'packagedxsnacks': 'Snacks',
 'packagxd snacks': 'Snacks',
 'packaxed snacks': 'Snacks',
 'paczaged snacks': 'Snacks',
 'psckaged snacks': 'Snacks',
 'pxckaged snacks': 'Snacks',
 'pzckaged snacks': 'Snacks',
 'saack': 'Snacks',
 'seack': 'Snacks',
 'seacks': 'Snacks',
 'snaak': 'Snacks',
 'snaaks': 'Snacks',
 'snack': 'Snacks',
 'snacks': 'Snacks',
 'snacss': 'Snacks',
 'snaczs': 'Snacks',
 'snaek': 'Snacks',
 'snaeks': 'Snacks',
 'snask': 'Snacks',
 'snaxk': 'Snacks',
 'snazk': 'Snacks',
 'snazks': 'Snacks',
 'snecks': 'Snacks',
 'snscks': 'Snacks',
 'snxck': 'Snacks',
 'snzck': 'Snacks',
 'ssack': 'Snacks',
 'ssacks': 'Snacks',
 'szack': 'Snacks'}

RETAILER_MAP = \
{'coanerstore inc': 'CornerStore',
 'cornarstore inc': 'CornerStore',
 'corner stoee': 'CornerStore',
 'corner store': 'CornerStore',
 'cornersaore inc': 'CornerStore',
 'cornerstere inc': 'CornerStore',
 'cornerstore': 'CornerStore',
 'cornerstore iec': 'CornerStore',
 'cornerstore inc': 'CornerStore',
 'cornerstore ixc': 'CornerStore',
 'cornerstorx inc': 'CornerStore',
 'cornerstorz inc': 'CornerStore',
 'cornerztore': 'CornerStore',
 'cornesstore': 'CornerStore',
 'cornexstore inc': 'CornerStore',
 'cornxrstore inc': 'CornerStore',
 'cosnerstore': 'CornerStore',
 'coxner store': 'CornerStore',
 'cozner store': 'CornerStore',
 'czrnerstore': 'CornerStore',
 'daalyshop': 'DailyShop',
 'daelyshop': 'DailyShop',
 'daelyshop local': 'DailyShop',
 'daiay-shop': 'DailyShop',
 'dailashop': 'DailyShop',
 'daily seop': 'DailyShop',
 'daily shop': 'DailyShop',
 'daily szop': 'DailyShop',
 'daily-seop': 'DailyShop',
 'daily-shap': 'DailyShop',
 'daily-shop': 'DailyShop',
 'daily-shxp': 'DailyShop',
 'dailysaop': 'DailyShop',
 'dailyshop': 'DailyShop',
 'dailyshop lecal': 'DailyShop',
 'dailyshop local': 'DailyShop',
 'dailyshop loeal': 'DailyShop',
 'dailyshop lscal': 'DailyShop',
 'dailyshopalocal': 'DailyShop',
 'dailyshopelocal': 'DailyShop',
 'dailyshxp': 'DailyShop',
 'dailyszop': 'DailyShop',
 'daizy shop': 'DailyShop',
 'dasly shop': 'DailyShop',
 'daxlyshop': 'DailyShop',
 'dsily shop': 'DailyShop',
 'dxily-shop': 'DailyShop',
 'dzily shop': 'DailyShop',
 'dzilyshop': 'DailyShop',
 'faesh grocer': 'FreshGrocer',
 'freeh gr': 'FreshGrocer',
 'freeh grocer': 'FreshGrocer',
 'freehgrocer': 'FreshGrocer',
 'fresh arocer': 'FreshGrocer',
 'fresh gaocer': 'FreshGrocer',
 'fresh geocer': 'FreshGrocer',
 'fresh gr': 'FreshGrocer',
 'fresh grocer': 'FreshGrocer',
 'fresh groczr': 'FreshGrocer',
 'fresh grzcer': 'FreshGrocer',
 'fresh xrocer': 'FreshGrocer',
 'freshgeocer': 'FreshGrocer',
 'freshgracer llc': 'FreshGrocer',
 'freshgrocea llc': 'FreshGrocer',
 'freshgrocer': 'FreshGrocer',
 'freshgrocer lec': 'FreshGrocer',
 'freshgrocer llc': 'FreshGrocer',
 'freshgrocerxllc': 'FreshGrocer',
 'freshgrocerzllc': 'FreshGrocer',
 'freshgrocxr': 'FreshGrocer',
 'freshgrzcer': 'FreshGrocer',
 'freshgxocer': 'FreshGrocer',
 'freshgxocer llc': 'FreshGrocer',
 'freshgzocer': 'FreshGrocer',
 'freshgzocer llc': 'FreshGrocer',
 'freshxrocer': 'FreshGrocer',
 'fresz gr': 'FreshGrocer',
 'freszgrocer': 'FreshGrocer',
 'frexh grocer': 'FreshGrocer',
 'frezh grocer': 'FreshGrocer',
 'frssh gr': 'FreshGrocer',
 'frxsh gr': 'FreshGrocer',
 'fxesh gr': 'FreshGrocer',
 'fxesh grocer': 'FreshGrocer',
 'gaant': 'GiantStore',
 'gaant corp': 'GiantStore',
 'geant corp': 'GiantStore',
 'giaet store': 'GiantStore',
 'giaetstore': 'GiantStore',
 'gianastore': 'GiantStore',
 'giane corp': 'GiantStore',
 'gians corp': 'GiantStore',
 'giant': 'GiantStore',
 'giant atore': 'GiantStore',
 'giant corp': 'GiantStore',
 'giant etore': 'GiantStore',
 'giant store': 'GiantStore',
 'giant stoze': 'GiantStore',
 'giant xtore': 'GiantStore',
 'giantestore': 'GiantStore',
 'giantstore': 'GiantStore',
 'giantszore': 'GiantStore',
 'gianxstore': 'GiantStore',
 'gient': 'GiantStore',
 'gient store': 'GiantStore',
 'giznt': 'GiantStore',
 'gsant': 'GiantStore',
 'gsant store': 'GiantStore',
 'gzant': 'GiantStore',
 'meea mart': 'MegaMart',
 'mega mart': 'MegaMart',
 'mega mxrt': 'MegaMart',
 'megaamart': 'MegaMart',
 'megamaat': 'MegaMart',
 'megamart': 'MegaMart',
 'megamart inc': 'MegaMart',
 'megamart inc.': 'MegaMart',
 'megamart ins.': 'MegaMart',
 'megamart supercenters': 'MegaMart',
 'megamart supercenxers': 'MegaMart',
 'megamart supercenzers': 'MegaMart',
 'megamart supersenters': 'MegaMart',
 'megamart znc.': 'MegaMart',
 'megamarx inc.': 'MegaMart',
 'megamast': 'MegaMart',
 'megamaxt': 'MegaMart',
 'megamxrt': 'MegaMart',
 'megaxmart': 'MegaMart',
 'megazart supercenters': 'MegaMart',
 'mege mart': 'MegaMart',
 'megzmart inc.': 'MegaMart',
 'mmaet': 'MegaMart',
 'mmart': 'MegaMart',
 'mmsrt': 'MegaMart',
 'msart': 'MegaMart',
 'msga mart': 'MegaMart',
 'mxart': 'MegaMart',
 'mzart': 'MegaMart',
 'mzgamart': 'MegaMart',
 'prime antry': 'PrimePantry',
 'prime pantry': 'PrimePantry',
 'prime pantry delivery': 'PrimePantry',
 'prime pantxy': 'PrimePantry',
 'prime pantzy': 'PrimePantry',
 'prime pnsry': 'PrimePantry',
 'prime pntry': 'PrimePantry',
 'prime pnxry': 'PrimePantry',
 'prime sntry': 'PrimePantry',
 'primepantry': 'PrimePantry',
 'primepantry delivery': 'PrimePantry',
 'primepantry delixery': 'PrimePantry',
 'primepantry dzlivery': 'PrimePantry',
 'primepantxy': 'PrimePantry',
 'primesantry': 'PrimePantry',
 'primexpantry': 'PrimePantry',
 'prims pantry': 'PrimePantry',
 'primz pantry': 'PrimePantry',
 'prize pantry': 'PrimePantry',
 'prsme pantry': 'PrimePantry',
 'prsme pntry': 'PrimePantry',
 'przme pantry': 'PrimePantry',
 'przmepantry': 'PrimePantry',
 'queckstop convenience': 'QuickStop',
 'quiak stop': 'QuickStop',
 'quicestop': 'QuickStop',
 'quick stop': 'QuickStop',
 'quick stsp': 'QuickStop',
 'quick-seop': 'QuickStop',
 'quick-ssop': 'QuickStop',
 'quick-step': 'QuickStop',
 'quick-stop': 'QuickStop',
 'quick-stsp': 'QuickStop',
 'quick-szop': 'QuickStop',
 'quickestop': 'QuickStop',
 'quicketop': 'QuickStop',
 'quicksaop convenience': 'QuickStop',
 'quickseop': 'QuickStop',
 'quickstep': 'QuickStop',
 'quickstop': 'QuickStop',
 'quickstop coevenience': 'QuickStop',
 'quickstop conaenience': 'QuickStop',
 'quickstop conveeience': 'QuickStop',
 'quickstop convenience': 'QuickStop',
 'quickstop conveniezce': 'QuickStop',
 'quickstop convesience': 'QuickStop',
 'quickstop sonvenience': 'QuickStop',
 'quickstxp': 'QuickStop',
 'quickxtop convenience': 'QuickStop',
 'quicsstop': 'QuickStop',
 'quisk-stop': 'QuickStop',
 'quixk-stop': 'QuickStop',
 'qzick-stop': 'QuickStop',
 'qzickstop': 'QuickStop',
 'tee giant store': 'GiantStore',
 'the coaner store': 'CornerStore',
 'the corner stoae': 'CornerStore',
 'the corner store': 'CornerStore',
 'the corser store': 'CornerStore',
 'the eorner store': 'CornerStore',
 'the gaant store': 'GiantStore',
 'the giant atore': 'GiantStore',
 'the giant seore': 'GiantStore',
 'the giant stare': 'GiantStore',
 'the giant store': 'GiantStore',
 'the giaxt store': 'GiantStore',
 'the gzant store': 'GiantStore',
 'the siant store': 'GiantStore',
 'tze corner store': 'CornerStore',
 'tze giant store': 'GiantStore',
 'weacart.com': 'WebCart',
 'web cart': 'WebCart',
 'web cast': 'WebCart',
 'web cert': 'WebCart',
 'web sart': 'WebCart',
 'web xart': 'WebCart',
 'webcaat.com': 'WebCart',
 'webcaet': 'WebCart',
 'webcart': 'WebCart',
 'webcart online': 'WebCart',
 'webcart onlixe': 'WebCart',
 'webcart onlize': 'WebCart',
 'webcart ozline': 'WebCart',
 'webcart.com': 'WebCart',
 'webcart.csm': 'WebCart',
 'webcert.com': 'WebCart',
 'webcxrt': 'WebCart',
 'webczrt.com': 'WebCart',
 'webeart.com': 'WebCart',
 'websart': 'WebCart',
 'websart.com': 'WebCart',
 'wes cart': 'WebCart',
 'wescart': 'WebCart',
 'wexcart.com': 'WebCart',
 'wezcart.com': 'WebCart',
 'wsbcart': 'WebCart',
 'wsbcart.com': 'WebCart'}

VARIANT_MAP = \
{'0': 'Zero Sugar',
 'BARxEQUE': 'BBQ',
 'CC': 'Chocolate Chip',
 'CHEReY': 'Cherry',
 'CHaRRY': 'Cherry',
 'CHsRY': 'Cherry',
 'CHzY': 'Cherry',
 'CITzS': 'Citrus',
 'CIsRUS': 'Citrus',
 'CLeSSC': 'Classic',
 'CaSSC': 'Classic',
 'Caassc': 'Classic',
 'Caassic': 'Classic',
 'Cars': 'Classic',
 'Cassc': 'Classic',
 'Catrs': 'Citrus',
 'CeTRUS': 'Citrus',
 'Ceassc': 'Classic',
 'Cers': 'Classic',
 'Cessc': 'Classic',
 'Cetrus': 'Citrus',
 'CsASSIC': 'Classic',
 'CsSSC': 'Classic',
 'Csassic': 'Classic',
 'Cxassc': 'Classic',
 'CxocoChip': 'Chocolate Chip',
 'Cxssc': 'Classic',
 'CzocoChip': 'Chocolate Chip',
 'Czssc': 'Classic',
 'DBL zHOCO': 'Double Choco',
 'DIaT': 'Diet',
 'DOUaLECHOCO': 'Double Choco',
 'DOsBLECHOCO': 'Double Choco',
 'DOxBLECHOCO': 'Double Choco',
 'DaUBLECHOCO': 'Double Choco',
 'Dal Chc': 'Double Choco',
 'DaubleChoco': 'Double Choco',
 'Dba Chc': 'Double Choco',
 'Dba Choco': 'Double Choco',
 'Dbe Chc': 'Double Choco',
 'Dbl Chaco': 'Double Choco',
 'Dbl Choeo': 'Double Choco',
 'Dbl Choxo': 'Double Choco',
 'Dbl Chozo': 'Double Choco',
 'Dbl Chsco': 'Double Choco',
 'Dbl Chxco': 'Double Choco',
 'Dbl Csc': 'Double Choco',
 'Dbl Cxc': 'Double Choco',
 'Dbl ahc': 'Double Choco',
 'Dbl ahoco': 'Double Choco',
 'Dbl xhc': 'Double Choco',
 'Dbl zhc': 'Double Choco',
 'DbleChc': 'Double Choco',
 'DblsChoco': 'Double Choco',
 'DblxChc': 'Double Choco',
 'DblzChoco': 'Double Choco',
 'Dbs Chc': 'Double Choco',
 'Dbz Chc': 'Double Choco',
 'Dbz Choco': 'Double Choco',
 'Deet': 'Diet',
 'Del Choco': 'Double Choco',
 'Diat': 'Diet',
 'Dist': 'Diet',
 'DoableChoco': 'Double Choco',
 'DoebleChoco': 'Double Choco',
 'DoualeChoco': 'Double Choco',
 'Doubee Choco': 'Double Choco',
 'DoubeeChoco': 'Double Choco',
 'Doubla Choco': 'Double Choco',
 'DoublaChoco': 'Double Choco',
 'DoubleCaoco': 'Double Choco',
 'DoubleCheco': 'Double Choco',
 'DsL CHC': 'Double Choco',
 'Dset': 'Diet',
 'Dsl Chc': 'Double Choco',
 'DsubleChoco': 'Double Choco',
 'DxET': 'Diet',
 'Dzet': 'Diet',
 'FRENCH VANIaLA': 'French Vanilla',
 'FREeCH VANILLA': 'French Vanilla',
 'FaAMIN': 'Flamin Hot',
 'FeAMIN': 'Flamin Hot',
 'Feamin': 'Flamin Hot',
 'Feench Vanilla': 'French Vanilla',
 'Flaman': 'Flamin Hot',
 'Flamsn': 'Flamin Hot',
 'Flasin': 'Flamin Hot',
 'Flaxin': 'Flamin Hot',
 'Flsmin': 'Flamin Hot',
 'Flzmin': 'Flamin Hot',
 'Freach Vanilla': 'French Vanilla',
 'Freech Vanilla': 'French Vanilla',
 'Frenca Vanilla': 'French Vanilla',
 'Frence Vanilla': 'French Vanilla',
 'Fsamin': 'Flamin Hot',
 'Fxamin': 'Flamin Hot',
 'HOT': 'Hot',
 'HoneyeBBQ': 'Honey BBQ',
 'HoneysBBQ': 'Honey BBQ',
 'HoneyzBBQ': 'Honey BBQ',
 'Honsy BBQ': 'Honey BBQ',
 'Hosey BBQ': 'Honey BBQ',
 'Hot': 'Hot',
 'Hsney BBQ': 'Honey BBQ',
 'Hxney BBQ': 'Honey BBQ',
 'Hzney BBQ': 'Honey BBQ',
 'LEMON-LIsE': 'Lemon-Lime',
 'LEMaN-LIME': 'Lemon-Lime',
 'LIsE': 'Lemon-Lime',
 'Leman-Lime': 'Lemon-Lime',
 'Lemon-Lame': 'Lemon-Lime',
 'Lemon-Lise': 'Lemon-Lime',
 'Lemoz-Lime': 'Lemon-Lime',
 'Lete': 'Lemon-Lime',
 'Liae': 'Lemon-Lime',
 'Lise': 'Lemon-Lime',
 'Lzte': 'Lemon-Lime',
 'MIXED BsRRY': 'Mixed Berry',
 'MIXED xERRY': 'Mixed Berry',
 'NO SUGeR': 'No Sugar',
 'Ne Sugar': 'No Sugar',
 'OAT': 'Oatmeal Raisin',
 'OATMaAL': 'Oatmeal Raisin',
 'OATxL': 'Oatmeal Raisin',
 'OAaMEAL RAISIN': 'Oatmeal Raisin',
 'OAaML': 'Oatmeal Raisin',
 'Oaaml': 'Oatmeal Raisin',
 'Oaemeal Raisin': 'Oatmeal Raisin',
 'Oaeml': 'Oatmeal Raisin',
 'Oaig': 'Oatmeal Raisin',
 'Oaiginal': 'Oatmeal Raisin',
 'Oasml': 'Oatmeal Raisin',
 'Oat': 'Oatmeal Raisin',
 'Oataeal': 'Oatmeal Raisin',
 'Oataeal Raisin': 'Oatmeal Raisin',
 'Oatal': 'Oatmeal Raisin',
 'Oatmaal': 'Oatmeal Raisin',
 'Oatmeaa Raisin': 'Oatmeal Raisin',
 'Oatmeal Raiszn': 'Oatmeal Raisin',
 'Oatmesl': 'Oatmeal Raisin',
 'Oatmzal Raisin': 'Oatmeal Raisin',
 'Oatxeal': 'Oatmeal Raisin',
 'Oatxl': 'Oatmeal Raisin',
 'Oatzeal': 'Oatmeal Raisin',
 'Oatzl': 'Oatmeal Raisin',
 'Oaxmeal': 'Oatmeal Raisin',
 'Oazmeal': 'Oatmeal Raisin',
 'Oazml': 'Oatmeal Raisin',
 'OeTML': 'Oatmeal Raisin',
 'Oenl': 'Oatmeal Raisin',
 'Oetmeal': 'Oatmeal Raisin',
 'Oetmeal Raisin': 'Oatmeal Raisin',
 'Oetml': 'Oatmeal Raisin',
 'Original aalted': 'Original Salted',
 'Original xalted': 'Original Salted',
 'Ostmeal': 'Oatmeal Raisin',
 'Ostml': 'Oatmeal Raisin',
 'OxTMEAL': 'Oatmeal Raisin',
 'Oxtml': 'Oatmeal Raisin',
 'OzTML': 'Oatmeal Raisin',
 'Oztmeal': 'Oatmeal Raisin',
 'Oztml': 'Oatmeal Raisin',
 'RExULAR': 'Regular',
 'SALTzD': 'Salted',
 'SAeT': 'Salted',
 'SAeTED': 'Salted',
 'SAzTED': 'Salted',
 'SC &eOnion': 'SC & Onion',
 'SC &sOnion': 'SC & Onion',
 'SC &xOnion': 'SC & Onion',
 'SCz& Onion': 'SC & Onion',
 'SF': 'Sugar Free',
 'SLzD': 'Salted',
 'SOURxCRM': 'Sour Cream',
 'SOzR CREAM': 'Sour Cream',
 'SPaCY': 'Spicy',
 'SUGARFRaE': 'Sugar Free',
 'SUGARFRsE': 'Sugar Free',
 'SUGARFsEE': 'Sugar Free',
 'SUGARFxEE': 'Sugar Free',
 'SUGAaFREE': 'Sugar Free',
 'SUGxRFREE': 'Sugar Free',
 'SUeAR FREE': 'Sugar Free',
 'Saandard': 'Standard',
 'Saat': 'Salted',
 'Saet': 'Salted',
 'Salaed': 'Salted',
 'Se & ONION': 'SC & Onion',
 'Seur Cream': 'Sour Cream',
 'Slad': 'Salted',
 'Slsd': 'Salted',
 'Slxd': 'Salted',
 'Slzd': 'Salted',
 'Soue Crm': 'Sour Cream',
 'Sour Caeam': 'Sour Cream',
 'Sour aream': 'Sour Cream',
 'Sour erm': 'Sour Cream',
 'Sour srm': 'Sour Cream',
 'Sour zream': 'Sour Cream',
 'Sour zrm': 'Sour Cream',
 'SourCeeam': 'Sour Cream',
 'SourCraam': 'Sour Cream',
 'Souraream': 'Sour Cream',
 'SoureCream': 'Sour Cream',
 'Soureream': 'Sour Cream',
 'SoursCream': 'Sour Cream',
 'Soursream': 'Sour Cream',
 'Sous Crm': 'Sour Cream',
 'SouxCream': 'Sour Cream',
 'SouzCream': 'Sour Cream',
 'Soxr Cream': 'Sour Cream',
 'Soxr Crm': 'Sour Cream',
 'SoxrCream': 'Sour Cream',
 'SozrCream': 'Sour Cream',
 'SsCY': 'Spicy',
 'SsLT': 'Salted',
 'Ssandard': 'Standard',
 'Sscy': 'Spicy',
 'SsgarFree': 'Sugar Free',
 'Sslted': 'Salted',
 'Sstd': 'Standard',
 'SsurCream': 'Sour Cream',
 'SuaarFree': 'Sugar Free',
 'Sugar Faee': 'Sugar Free',
 'Sugar Frxe': 'Sugar Free',
 'Sugar eree': 'Sugar Free',
 'Sugar zree': 'Sugar Free',
 'SugarFaee': 'Sugar Free',
 'SugarFrze': 'Sugar Free',
 'SugarFsee': 'Sugar Free',
 'Sugareree': 'Sugar Free',
 'Sugsr Free': 'Sugar Free',
 'SxCY': 'Spicy',
 'Sxandard': 'Standard',
 'SxgarFree': 'Sugar Free',
 'Szandard': 'Standard',
 'Szgar Free': 'Sugar Free',
 'Szicy': 'Spicy',
 'Szlt': 'Salted',
 'Szlted': 'Salted',
 'Szur Cream': 'Sour Cream',
 'Szur Crm': 'Sour Cream',
 'SzurCream': 'Sour Cream',
 'VANILaA': 'Vanilla',
 'VANzLLA': 'Vanilla',
 'VNsA': 'Vanilla',
 'Vaailla': 'Vanilla',
 'Vala': 'Vanilla',
 'Vela': 'Vanilla',
 'Vnaa': 'Vanilla',
 'Vnea': 'Vanilla',
 'Vnsa': 'Vanilla',
 'Vnxa': 'Vanilla',
 'Vsla': 'Vanilla',
 'Vsnilla': 'Vanilla',
 'VxLA': 'Vanilla',
 'Vxla': 'Vanilla',
 'VzLA': 'Vanilla',
 'Vzla': 'Vanilla',
 'WILz CHERRY': 'Wild Cherry',
 'ZERO SUxAR': 'Zero Sugar',
 'ZEROaSUGAR': 'Zero Sugar',
 'ZEROsSUGAR': 'Zero Sugar',
 'ZEROzCAL': 'Zero Cal',
 'ZEsO': 'Zero Sugar',
 'Zaro': 'Zero Sugar',
 'Zeao': 'Zero Sugar',
 'Zeeo': 'Zero Sugar',
 'Zeeo Sugar': 'Zero Sugar',
 'Zera Sugar': 'Zero Sugar',
 'Zere Sugar': 'Zero Sugar',
 'Zero Suger': 'Zero Sugar',
 'Zero Sxgar': 'Zero Sugar',
 'Zero Szgar': 'Zero Sugar',
 'Zero augar': 'Zero Sugar',
 'Zero xugar': 'Zero Sugar',
 'Zers Sugar': 'Zero Sugar',
 'Zeso': 'Zero Sugar',
 'Zeso Sugar': 'Zero Sugar',
 'Zexo': 'Zero Sugar',
 'Zezo': 'Zero Sugar',
 'Zsro': 'Zero Sugar',
 'Zsro Sugar': 'Zero Sugar',
 'ZxRO': 'Zero Sugar',
 'ZxRO CAL': 'Zero Cal',
 'Zxro Sugar': 'Zero Sugar',
 'ZzRO': 'Zero Sugar',
 'Zzro': 'Zero Sugar',
 'Zzro Cal': 'Zero Cal',
 'bARBECsE': 'BBQ',
 'bARBEaUE': 'BBQ',
 'bAsBECUE': 'BBQ',
 'baee': 'Base',
 'baraeque': 'BBQ',
 'barbaque': 'BBQ',
 'barbecae': 'BBQ',
 'barbecee': 'BBQ',
 'barbecue': 'BBQ',
 'barbecxe': 'BBQ',
 'barbecze': 'BBQ',
 'barbeeue': 'BBQ',
 'barbeqae': 'BBQ',
 'barbeqee': 'BBQ',
 'barbeque': 'BBQ',
 'barbeqxe': 'BBQ',
 'barbeqze': 'BBQ',
 'barbexue': 'BBQ',
 'barbezue': 'BBQ',
 'barbq': 'BBQ',
 'barbsque': 'BBQ',
 'barbxcue': 'BBQ',
 'barbzcue': 'BBQ',
 'barbzque': 'BBQ',
 'barry': 'Berry',
 'barsecue': 'BBQ',
 'barseque': 'BBQ',
 'bary': 'Berry',
 'basbeque': 'BBQ',
 'base': 'Base',
 'baxe': 'Base',
 'bazbecue': 'BBQ',
 'baze': 'Base',
 'bbq': 'BBQ',
 'beary': 'Berry',
 'beay': 'Berry',
 'beery': 'Berry',
 'beey': 'Berry',
 'beray': 'Berry',
 'berbecue': 'BBQ',
 'berbeque': 'BBQ',
 'berry': 'Berry',
 'berxy': 'Berry',
 'bery': 'Berry',
 'berzy': 'Berry',
 'bese': 'Base',
 'besry': 'Berry',
 'besy': 'Berry',
 'bexry': 'Berry',
 'bexy': 'Berry',
 'bezry': 'Berry',
 'bezy': 'Berry',
 'bry': 'Berry',
 'bsry': 'Berry',
 'bsse': 'Base',
 'bxrbecue': 'BBQ',
 'bxrry': 'Berry',
 'bxry': 'Berry',
 'bxse': 'Base',
 'bzRBECUE': 'BBQ',
 'bzrbeque': 'BBQ',
 'bzrry': 'Berry',
 'bzry': 'Berry',
 'bzse': 'Base',
 'cHERaY': 'Cherry',
 'cHEeY': 'Cherry',
 'cHExRY': 'Cherry',
 'cHOCO cHaP': 'Chocolate Chip',
 'cHOCeLATE cHIP': 'Chocolate Chip',
 'cHOCx cHIP': 'Chocolate Chip',
 'cHxCO cHIP': 'Chocolate Chip',
 'cHxCOcHIP': 'Chocolate Chip',
 'cHzRRY': 'Cherry',
 'cIsRUS': 'Citrus',
 'cIzRUS': 'Citrus',
 'cLAxSC': 'Classic',
 'caRS': 'Classic',
 'caTRS': 'Classic',
 'caassc': 'Classic',
 'caerry': 'Cherry',
 'caery': 'Cherry',
 'caocochip': 'Chocolate Chip',
 'catrus': 'Citrus',
 'ceOCOcHIP': 'Chocolate Chip',
 'ceassc': 'Classic',
 'ceery': 'Cherry',
 'chaco chip': 'Chocolate Chip',
 'chacochip': 'Chocolate Chip',
 'chary': 'Cherry',
 'chay': 'Cherry',
 'cheary': 'Cherry',
 'cheay': 'Cherry',
 'checo': 'Cherry',
 'checo chip': 'Chocolate Chip',
 'checochip': 'Chocolate Chip',
 'checolate chip': 'Chocolate Chip',
 'cheery': 'Cherry',
 'cheray': 'Cherry',
 'cherey': 'Cherry',
 'cherry': 'Cherry',
 'chersy': 'Cherry',
 'cherxy': 'Cherry',
 'chery': 'Cherry',
 'cherzy': 'Cherry',
 'chesy': 'Cherry',
 'chexy': 'Cherry',
 'chey': 'Cherry',
 'chezry': 'Cherry',
 'choao chip': 'Chocolate Chip',
 'choca chip': 'Chocolate Chip',
 'chocachip': 'Chocolate Chip',
 'chocechip': 'Chocolate Chip',
 'choco caip': 'Chocolate Chip',
 'choco ceip': 'Chocolate Chip',
 'choco chep': 'Chocolate Chip',
 'choco chip': 'Chocolate Chip',
 'choco chzp': 'Chocolate Chip',
 'choco csip': 'Chocolate Chip',
 'choco cxip': 'Chocolate Chip',
 'choco ehip': 'Chocolate Chip',
 'choco ship': 'Chocolate Chip',
 'choco zhip': 'Chocolate Chip',
 'chocoachip': 'Chocolate Chip',
 'chococeip': 'Chocolate Chip',
 'chocochap': 'Chocolate Chip',
 'chocochip': 'Chocolate Chip',
 'chocochsp': 'Chocolate Chip',
 'chocochxp': 'Chocolate Chip',
 'chocochzp': 'Chocolate Chip',
 'chococsip': 'Chocolate Chip',
 'chococxip': 'Chocolate Chip',
 'chococzip': 'Chocolate Chip',
 'chocoechip': 'Chocolate Chip',
 'chocolaae chip': 'Chocolate Chip',
 'chocolate chip': 'Chocolate Chip',
 'chocolate cxip': 'Chocolate Chip',
 'chocolate czip': 'Chocolate Chip',
 'chocolate ship': 'Chocolate Chip',
 'chocolate zhip': 'Chocolate Chip',
 'chocolateachip': 'Chocolate Chip',
 'chocolateechip': 'Chocolate Chip',
 'chocolats chip': 'Chocolate Chip',
 'chocolatz chip': 'Chocolate Chip',
 'chocolaze chip': 'Chocolate Chip',
 'chocolste chip': 'Chocolate Chip',
 'chocolxte chip': 'Chocolate Chip',
 'chocolzte chip': 'Chocolate Chip',
 'chocoship': 'Chocolate Chip',
 'chocoxate chip': 'Chocolate Chip',
 'chocoxhip': 'Chocolate Chip',
 'chocozate chip': 'Chocolate Chip',
 'chocslate chip': 'Chocolate Chip',
 'chocz chip': 'Chocolate Chip',
 'choczlate chip': 'Chocolate Chip',
 'choeo chip': 'Chocolate Chip',
 'choso chip': 'Chocolate Chip',
 'chosochip': 'Chocolate Chip',
 'chrry': 'Cherry',
 'chry': 'Cherry',
 'chscochip': 'Chocolate Chip',
 'chscolate chip': 'Chocolate Chip',
 'chxcolate chip': 'Chocolate Chip',
 'chxry': 'Cherry',
 'chxy': 'Cherry',
 'chzco chip': 'Chocolate Chip',
 'chzcochip': 'Chocolate Chip',
 'chzcolate chip': 'Chocolate Chip',
 'chzry': 'Cherry',
 'ciarus': 'Citrus',
 'ciers': 'Citrus',
 'cierus': 'Citrus',
 'cisrs': 'Citrus',
 'citas': 'Citrus',
 'citaus': 'Citrus',
 'cites': 'Citrus',
 'citras': 'Citrus',
 'citres': 'Citrus',
 'citrs': 'Citrus',
 'citrss': 'Citrus',
 'citrus': 'Citrus',
 'citrxs': 'Citrus',
 'citrzs': 'Citrus',
 'citsus': 'Citrus',
 'citxs': 'Citrus',
 'citxus': 'Citrus',
 'citzus': 'Citrus',
 'cixrs': 'Citrus',
 'cixrus': 'Citrus',
 'claasc': 'Classic',
 'claesc': 'Classic',
 'claesic': 'Classic',
 'clasac': 'Classic',
 'clasaic': 'Classic',
 'clasc': 'Classic',
 'clasec': 'Classic',
 'claseic': 'Classic',
 'classac': 'Classic',
 'classc': 'Classic',
 'classec': 'Classic',
 'classic': 'Classic',
 'classsc': 'Classic',
 'classxc': 'Classic',
 'clasxc': 'Classic',
 'clasxic': 'Classic',
 'claszc': 'Classic',
 'claszic': 'Classic',
 'claxsic': 'Classic',
 'clazsc': 'Classic',
 'clazsic': 'Classic',
 'clesc': 'Classic',
 'clessic': 'Classic',
 'clsac': 'Classic',
 'clsec': 'Classic',
 'clssc': 'Classic',
 'clsssic': 'Classic',
 'clszc': 'Classic',
 'clxsc': 'Classic',
 'clxssic': 'Classic',
 'clzsc': 'Classic',
 'clzssc': 'Classic',
 'clzssic': 'Classic',
 'csTRUS': 'Citrus',
 'csassc': 'Classic',
 'cserry': 'Cherry',
 'csery': 'Cherry',
 'csry': 'Cherry',
 'ctrs': 'Citrus',
 'cxassic': 'Classic',
 'cxery': 'Cherry',
 'cxry': 'Cherry',
 'czery': 'Cherry',
 'czry': 'Cherry',
 'cztrus': 'Citrus',
 'dBL csOCO': 'Double Choco',
 'dBLecHC': 'Double Choco',
 'dBLxcHC': 'Double Choco',
 'dOUBLE xHOCO': 'Double Choco',
 'dOUBLEcHsCO': 'Double Choco',
 'dOUsLEcHOCO': 'Double Choco',
 'dOeBLEcHOCO': 'Double Choco',
 'daet': 'Diet',
 'dbe chc': 'Double Choco',
 'dbe choco': 'Double Choco',
 'dbl ceoco': 'Double Choco',
 'dbl chc': 'Double Choco',
 'dbl chcoco': 'Double Choco',
 'dbl choco': 'Double Choco',
 'dbl choso': 'Double Choco',
 'dbl czoco': 'Double Choco',
 'dbl xhoco': 'Double Choco',
 'dblechoco': 'Double Choco',
 'dblxchoco': 'Double Choco',
 'dbx chc': 'Double Choco',
 'deL cHC': 'Double Choco',
 'del choco': 'Double Choco',
 'diet': 'Diet',
 'dist': 'Diet',
 'dixt': 'Diet',
 'dizt': 'Diet',
 'double caoco': 'Double Choco',
 'double chaco': 'Double Choco',
 'double checo': 'Double Choco',
 'double choco': 'Double Choco',
 'double choso': 'Double Choco',
 'double chzco': 'Double Choco',
 'double csoco': 'Double Choco',
 'double cxoco': 'Double Choco',
 'double czoco': 'Double Choco',
 'doubleceoco': 'Double Choco',
 'doublechaco': 'Double Choco',
 'doublechoco': 'Double Choco',
 'doublechoxo': 'Double Choco',
 'doublecxoco': 'Double Choco',
 'doublexhoco': 'Double Choco',
 'doublx choco': 'Double Choco',
 'doublxchoco': 'Double Choco',
 'doubsechoco': 'Double Choco',
 'doubxe choco': 'Double Choco',
 'dousle choco': 'Double Choco',
 'doxble choco': 'Double Choco',
 'doxblechoco': 'Double Choco',
 'dozble choco': 'Double Choco',
 'dset': 'Diet',
 'dt': 'Diet',
 'dzL cHC': 'Double Choco',
 'dzet': 'Diet',
 'dzl chc': 'Double Choco',
 'dzuble choco': 'Double Choco',
 'dzublechoco': 'Double Choco',
 'fLAsIN': 'Flamin Hot',
 'fRENCH vANILaA': 'French Vanilla',
 'fRENCH zANILLA': 'French Vanilla',
 'fREsCH vANILLA': 'French Vanilla',
 'fRaNCH vANILLA': 'French Vanilla',
 'faench vanilla': 'French Vanilla',
 'flamin': 'Flamin Hot',
 'flamin hot': 'Flamin Hot',
 'flaming': 'Flamin Hot',
 'flamxn': 'Flamin Hot',
 'flamzn': 'Flamin Hot',
 'flazin': 'Flamin Hot',
 'flsmin': 'Flamin Hot',
 'flxmin': 'Flamin Hot',
 'freach vanilla': 'French Vanilla',
 'french eanilla': 'Vanilla',
 'french vanella': 'Vanilla',
 'french vaniala': 'French Vanilla',
 'french vaniela': 'Vanilla',
 'french vanilea': 'French Vanilla',
 'french vanilla': 'Vanilla',
 'french vanilxa': 'French Vanilla',
 'french vanilza': 'Vanilla',
 'french vanslla': 'Vanilla',
 'french vanxlla': 'Vanilla',
 'french vanzlla': 'Vanilla',
 'french vasilla': 'Vanilla',
 'french vaxilla': 'Vanilla',
 'french venilla': 'French Vanilla',
 'french vxnilla': 'Vanilla',
 'french xanilla': 'Vanilla',
 'frenchsvanilla': 'Vanilla',
 'frenchxvanilla': 'Vanilla',
 'frenchzvanilla': 'Vanilla',
 'frencs vanilla': 'Vanilla',
 'frencz vanilla': 'Vanilla',
 'freneh vanilla': 'Vanilla',
 'frensh vanilla': 'French Vanilla',
 'frenxh vanilla': 'Vanilla',
 'frenzh vanilla': 'Vanilla',
 'frezch vanilla': 'Vanilla',
 'frxnch vanilla': 'Vanilla',
 'frznch vanilla': 'Vanilla',
 'hONEYebbq': 'Honey BBQ',
 'hOT': 'Hot',
 'heney bbq': 'Honey BBQ',
 'hoaey bbq': 'Honey BBQ',
 'hoeey bbq': 'Honey BBQ',
 'honay bbq': 'Honey BBQ',
 'honee bbq': 'Honey BBQ',
 'honex bbq': 'Honey BBQ',
 'honey baq': 'Honey BBQ',
 'honey bbq': 'Honey BBQ',
 'honey beq': 'Honey BBQ',
 'honey bzq': 'Honey BBQ',
 'honey ebq': 'Honey BBQ',
 'honey sbq': 'Honey BBQ',
 'honey zbq': 'Honey BBQ',
 'honeyabbq': 'Honey BBQ',
 'hot': 'Hot',
 'lEMONelIME': 'Lemon-Lime',
 'leman lime': 'Lemon-Lime',
 'leman-lime': 'Lemon-Lime',
 'lemen-lime': 'Lemon-Lime',
 'lemon lame': 'Lemon-Lime',
 'lemon lime': 'Lemon-Lime',
 'lemon lise': 'Lemon-Lime',
 'lemon-aime': 'Lemon-Lime',
 'lemon-liae': 'Lemon-Lime',
 'lemon-lime': 'Lemon-Lime',
 'lemon-lsme': 'Lemon-Lime',
 'lemon-lzme': 'Lemon-Lime',
 'lemon-sime': 'Lemon-Lime',
 'lemon-zime': 'Lemon-Lime',
 'lemonslime': 'Lemon-Lime',
 'lemonxlime': 'Lemon-Lime',
 'lemos-lime': 'Lemon-Lime',
 'lemoz lime': 'Lemon-Lime',
 'lemzn-lime': 'Lemon-Lime',
 'leson-lime': 'Lemon-Lime',
 'lexon-lime': 'Lemon-Lime',
 'liee': 'Lemon-Lime',
 'lite': 'Lite',
 'lixe': 'Lite',
 'lize': 'Lite',
 'lste': 'Lite',
 'lxte': 'Lite',
 'lzTE': 'Lemon-Lime',
 'mIXED bxRRY': 'Mixed Berry',
 'mixed beery': 'Mixed Berry',
 'mixed berry': 'Mixed Berry',
 'mixed besry': 'Mixed Berry',
 'mixedaberry': 'Mixed Berry',
 'mixedeberry': 'Mixed Berry',
 'mixzd berry': 'Mixed Berry',
 'mxxed berry': 'Mixed Berry',
 'mzxed berry': 'Mixed Berry',
 'no augar': 'No Sugar',
 'no eugar': 'Zero Sugar',
 'no segar': 'Zero Sugar',
 'no suear': 'Zero Sugar',
 'no sugar': 'Zero Sugar',
 'no sugsr': 'Zero Sugar',
 'no sugxr': 'Zero Sugar',
 'no sugzr': 'Zero Sugar',
 'no xugar': 'Zero Sugar',
 'no zugar': 'Zero Sugar',
 'noasugar': 'Zero Sugar',
 'noesugar': 'Zero Sugar',
 'nossugar': 'Zero Sugar',
 'nosugar': 'Zero Sugar',
 'noxsugar': 'Zero Sugar',
 'ns sugar': 'Zero Sugar',
 'nx sugar': 'Zero Sugar',
 'nz sugar': 'Zero Sugar',
 'oRIGINAL sAsTED': 'Original Salted',
 'oRIaINAL sALTED': 'Original Salted',
 'oanl': 'Original',
 'oat raisin': 'Oatmeal Raisin',
 'oatmeal': 'Oatmeal Raisin',
 'oatmeal raiain': 'Oatmeal Raisin',
 'oatmeal raisen': 'Oatmeal Raisin',
 'oatmeal raisin': 'Oatmeal Raisin',
 'oatmeal raissn': 'Oatmeal Raisin',
 'oatmeal raisxn': 'Oatmeal Raisin',
 'oatmeal raixin': 'Oatmeal Raisin',
 'oatmealsraisin': 'Oatmeal Raisin',
 'oatmeax raisin': 'Oatmeal Raisin',
 'oatmeaz raisin': 'Oatmeal Raisin',
 'oatmexl': 'Oatmeal Raisin',
 'oatmezl': 'Oatmeal Raisin',
 'oatmezl raisin': 'Oatmeal Raisin',
 'oatml': 'Oatmeal Raisin',
 'oatmxal': 'Oatmeal Raisin',
 'oatmzal': 'Oatmeal Raisin',
 'oatseal raisin': 'Oatmeal Raisin',
 'oeig': 'Original',
 'ognl': 'Original',
 'orag': 'Original',
 'oreg': 'Original',
 'oreginal': 'Original',
 'orieinal': 'Original',
 'orig': 'Original',
 'origiaal': 'Original',
 'origieal': 'Original',
 'originaa salted': 'Original Salted',
 'original': 'Original',
 'original salted': 'Original Salted',
 'original saltxd': 'Original Salted',
 'original saltzd': 'Original Salted',
 'original salzed': 'Original Salted',
 'original sazted': 'Original Salted',
 'original sxlted': 'Original Salted',
 'original szlted': 'Original Salted',
 'originas salted': 'Original Salted',
 'originel': 'Original',
 'originel salted': 'Original Salted',
 'originxl': 'Original',
 'originxl salted': 'Original Salted',
 'originzl': 'Original',
 'origisal': 'Original',
 'origixal': 'Original',
 'origizal': 'Original',
 'orignl': 'Original',
 'origsnal': 'Original',
 'origsnal salted': 'Original Salted',
 'origxnal': 'Original',
 'origznal': 'Original',
 'orisinal': 'Original',
 'orisinal salted': 'Original Salted',
 'orixinal salted': 'Original Salted',
 'orizinal salted': 'Original Salted',
 'orsginal': 'Original',
 'orxg': 'Original',
 'orxginal': 'Original',
 'orxginal salted': 'Original Salted',
 'orzg': 'Original',
 'orzginal': 'Original',
 'oxig': 'Original',
 'ozig': 'Original',
 'oziginal salted': 'Original Salted',
 'oznl': 'Original',
 'rEsULAR': 'Regular',
 'reaular': 'Regular',
 'reg': 'Regular',
 'regelar': 'Regular',
 'regslar': 'Regular',
 'reguear': 'Regular',
 'regular': 'Regular',
 'reguler': 'Regular',
 'regulsr': 'Regular',
 'regulxr': 'Regular',
 'regusar': 'Regular',
 'reguxar': 'Regular',
 'reguzar': 'Regular',
 'rxgular': 'Regular',
 'rzgular': 'Regular',
 'sAaT': 'Salted',
 'sAsTED': 'Salted',
 'sLeD': 'Salted',
 'sOUR ceEAM': 'Sour Cream',
 'sOUR cxM': 'Sour Cream',
 'sOUReREAM': 'Sour Cream',
 'sOURsREAM': 'Sour Cream',
 'sOUzcREAM': 'Sour Cream',
 'sPIsY': 'Spicy',
 'sUGARefREE': 'Sugar Free',
 'sUGARfaEE': 'Sugar Free',
 'saated': 'Salted',
 'sagar free': 'Zero Sugar',
 'sagarfree': 'Zero Sugar',
 'salsed': 'Salted',
 'salt': 'Salted',
 'saltad': 'Salted',
 'salted': 'Salted',
 'saltxd': 'Salted',
 'sast': 'Salted',
 'sasted': 'Salted',
 'satd': 'Salted',
 'saur cream': 'Sour Cream',
 'saur crm': 'Sour Cream',
 'saurcream': 'Sour Cream',
 'saxt': 'Salted',
 'saxted': 'Salted',
 'sazt': 'Salted',
 'sc & oeion': 'SC & Onion',
 'sc & onaon': 'SC & Onion',
 'sc & onian': 'SC & Onion',
 'sc & onion': 'SC & Onion',
 'sc & onxon': 'SC & Onion',
 'sc & onzon': 'SC & Onion',
 'sc & osion': 'SC & Onion',
 'sc & oxion': 'SC & Onion',
 'sc & ozion': 'SC & Onion',
 'sc & xnion': 'SC & Onion',
 'sc a onion': 'SC & Onion',
 'sc s onion': 'SC & Onion',
 'seandard': 'Standard',
 'secy': 'Spicy',
 'selt': 'Salted',
 'sf': 'Sugar Free',
 'sltd': 'Salted',
 'soar crm': 'Sour Cream',
 'soer cream': 'Sour Cream',
 'soer crm': 'Sour Cream',
 'sosr crm': 'Sour Cream',
 'soua cream': 'Sour Cream',
 'soua crm': 'Sour Cream',
 'souacream': 'Sour Cream',
 'sour cam': 'Sour Cream',
 'sour cem': 'Sour Cream',
 'sour cream': 'Sour Cream',
 'sour creem': 'Sour Cream',
 'sour crm': 'Sour Cream',
 'sour crsam': 'Sour Cream',
 'sour crxam': 'Sour Cream',
 'sour cseam': 'Sour Cream',
 'sour csm': 'Sour Cream',
 'sourcream': 'Sour Cream',
 'sourcreem': 'Sour Cream',
 'sourcrexm': 'Sour Cream',
 'sourcrxam': 'Sour Cream',
 'sourcrzam': 'Sour Cream',
 'sourcseam': 'Sour Cream',
 'sourczeam': 'Sour Cream',
 'sourxcream': 'Sour Cream',
 'sourzcream': 'Sour Cream',
 'sozr crm': 'Sour Cream',
 'spacy': 'Spicy',
 'spay': 'Spicy',
 'spcy': 'Spicy',
 'spey': 'Spicy',
 'spiay': 'Spicy',
 'spicy': 'Spicy',
 'spiey': 'Spicy',
 'spixy': 'Spicy',
 'spizy': 'Spicy',
 'spscy': 'Spicy',
 'spsy': 'Spicy',
 'spxcy': 'Spicy',
 'spxy': 'Spicy',
 'spzcy': 'Spicy',
 'spzy': 'Spicy',
 'ssGAR fREE': 'Sugar Free',
 'ssGARfREE': 'Sugar Free',
 'ssLT': 'Salted',
 'staadard': 'Standard',
 'staedard': 'Standard',
 'stanaard': 'Standard',
 'standaad': 'Standard',
 'standard': 'Standard',
 'standasd': 'Standard',
 'standaxd': 'Standard',
 'standazd': 'Standard',
 'standerd': 'Standard',
 'standsrd': 'Standard',
 'standxrd': 'Standard',
 'standzrd': 'Standard',
 'stanxard': 'Standard',
 'stanzard': 'Standard',
 'stasdard': 'Standard',
 'staxdard': 'Standard',
 'stazdard': 'Standard',
 'std': 'Standard',
 'stendard': 'Standard',
 'stsndard': 'Standard',
 'stxndard': 'Standard',
 'sugaa free': 'Sugar Free',
 'sugae free': 'Sugar Free',
 'sugar free': 'Zero Sugar',
 'sugar xree': 'Sugar Free',
 'sugarfree': 'Zero Sugar',
 'sugarfrze': 'Sugar Free',
 'sugarsree': 'Zero Sugar',
 'sugarxfree': 'Zero Sugar',
 'sugarxree': 'Sugar Free',
 'suxar free': 'Zero Sugar',
 'suzarfree': 'Zero Sugar',
 'sx & onion': 'SC & Onion',
 'sxLT': 'Salted',
 'sxcy': 'Spicy',
 'sxicy': 'Spicy',
 'szICY': 'Spicy',
 'szURcREAM': 'Sour Cream',
 'szgar free': 'Sugar Free',
 'vAeILLA': 'Vanilla',
 'vNsA': 'Vanilla',
 'vaLA': 'Vanilla',
 'van': 'Vanilla',
 'vanalla': 'Vanilla',
 'vanella': 'Vanilla',
 'vaniala': 'Vanilla',
 'vaniela': 'Vanilla',
 'vanilaa': 'Vanilla',
 'vanilea': 'Vanilla',
 'vanilla': 'Vanilla',
 'vanilsa': 'Vanilla',
 'vanilxa': 'Vanilla',
 'vanilza': 'Vanilla',
 'vanixla': 'Vanilla',
 'vanslla': 'Vanilla',
 'vanxlla': 'Vanilla',
 'vasilla': 'Vanilla',
 'vaxilla': 'Vanilla',
 'veLA': 'Vanilla',
 'vela': 'Vanilla',
 'venilla': 'Vanilla',
 'vnla': 'Vanilla',
 'vnza': 'Vanilla',
 'vsnilla': 'Vanilla',
 'vxla': 'Vanilla',
 'vxnilla': 'Vanilla',
 'vznilla': 'Vanilla',
 'wILz cHERRY': 'Wild Cherry',
 'weld cherry': 'Wild Cherry',
 'wiad cherry': 'Wild Cherry',
 'wild aherry': 'Wild Cherry',
 'wild caerry': 'Wild Cherry',
 'wild ceerry': 'Wild Cherry',
 'wild cheary': 'Wild Cherry',
 'wild cherey': 'Wild Cherry',
 'wild cherry': 'Wild Cherry',
 'wild chexry': 'Wild Cherry',
 'wild chsrry': 'Wild Cherry',
 'wild cserry': 'Wild Cherry',
 'wild eherry': 'Wild Cherry',
 'wild sherry': 'Wild Cherry',
 'wild zherry': 'Wild Cherry',
 'wildscherry': 'Wild Cherry',
 'wildxcherry': 'Wild Cherry',
 'wildzcherry': 'Wild Cherry',
 'wixd cherry': 'Wild Cherry',
 'wsld cherry': 'Wild Cherry',
 'wxld cherry': 'Wild Cherry',
 'wzld cherry': 'Wild Cherry',
 'zERO aUGAR': 'Zero Sugar',
 'zERO sAL': 'Zero Cal',
 'zaro': 'Zero Sugar',
 'zeao cal': 'Zero Cal',
 'zera cal': 'Zero Cal',
 'zero': 'Zero Sugar',
 'zero cal': 'Zero Cal',
 'zero czl': 'Zero Cal',
 'zero sugar': 'Zero Sugar',
 'zero suxar': 'Zero Sugar',
 'zero xal': 'Zero Cal',
 'zeroecal': 'Zero Cal',
 'zeroxcal': 'Zero Cal',
 'zers cal': 'Zero Cal',
 'zerx cal': 'Zero Cal',
 'zerz cal': 'Zero Cal',
 'zexo cal': 'Zero Cal',
 'zxRO': 'Zero Sugar',
 'zzRO cAL': 'Zero Cal'}

